rm -rf ~/.cache/screenshots/*                                                                                      
mpd &                                                                                                              
mpDris2 &                                                                                                          
sxhkd &                                                                                                            
unclutter &                                                                                                        
xwallpaper --no-randr --zoom ~/.config/pape.png                                                                    
lxsession &                                                                                                        
dwmblocks &                                                                                                        
exec dwm
